version: '3.3'

services:
  manager:
    image: manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5200:5200"
    environment:
    - ANALISA_SERVER=mongodb://jmsoft:x14r53p5!a@10.0.0.14:27017/evaluations
    - ANALISA_DATABASE=${ANALISA_DATABASE}
    - ANALISA_TOKENSERVER=${ANALISA_TOKENSERVER}
    - ANALISA_SIGNALRSERVICE=${ANALISA_SIGNALRSERVICE}
    - ANALISA_BLOBKEY=${ANALISA_BLOBKEY}
    - ANALISA_SENDGRIDKEY=${ANALISA_SENDGRIDKEY}
    - ANALISA_SERVERLOG=${ANALISA_SERVERLOG}
    - ANALISA_DATABASELOG=${ANALISA_DATABASELOG}
    - ANALISA_SERVERINTEGRATION=${ANALISA_SERVERINTEGRATION}
    - ANALISA_DATABASEINTEGRATION=${ANALISA_DATABASEINTEGRATION}
    - ANALISA_SERVICEBUSCONNECTIONSTRING=${ANALISA_SERVICEBUSCONNECTIONSTRING}
    - ANALISA_QUEUENAME=${ANALISA_QUEUENAME}

